-- Supabase schema aligned to spec (non-destructive, additive where possible)

create table if not exists public.profiles (
  id uuid primary key,
  username text,
  avatar_url text,
  created_at timestamp with time zone default now()
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id),
  title text not null,
  description text not null,
  price integer not null,
  category text not null,
  image_url text,
  created_at timestamp with time zone default now(),
  status text default 'selling' check (status in ('selling','reserved','sold'))
);

create table if not exists public.chat_rooms (
  id bigint generated by default as identity primary key,
  item_id bigint references public.items(id),
  buyer_id uuid references auth.users(id),
  seller_id uuid references auth.users(id),
  created_at timestamp with time zone default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id bigint references public.chat_rooms(id),
  sender_id uuid references auth.users(id),
  content text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.admin_events (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  date date,
  created_at timestamp with time zone default now()
);
