export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ITEM_LIST: '/items',
  ITEM_DETAIL: '/items/:id',
  ITEM_EDIT: '/items/:id/edit',
  EVENT_LIST: '/events',
  EVENT_DETAIL: '/events/:id',
  SELL: '/sell',
  MYPAGE: '/mypage',
  CHAT_LIST: '/chat',
  CHAT_ROOM: '/chat/:roomId',
  ADMIN: '/admin',
} as const;
