export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  ITEM_LIST: '/items',
  ITEM_DETAIL: '/items/:id',
  ITEM_EDIT: '/items/:id/edit',
  SELL: '/sell',
  MYPAGE: '/mypage',
  PROFILE_EDIT: '/mypage/edit',
  CHAT_LIST: '/chat',
  CHAT_ROOM: '/chat/:roomId',
  ADMIN: '/admin',
  ADMIN_ITEMS: '/admin/items',
  ADMIN_ORDERS: '/admin/orders',
} as const;
